name: ImageDataAnalysis

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - pandas
  - scikit-image
  - matplotlib-base
  - pip
  # conda_spec
  - jupyterlab
  - pip:
    # pip_core
    # pip_spec